### ISSUE TITLE
Proposed agenda and acceptance of papers

### ISSUE THREAD

**Issue by nniiicc** [sig-cm/ASIST-2020#13]
Each workshop day consists of 4 hours:
- 3 x Full  (45 min each - 15 presentation / 30 workshop) 
- 2 x Short  (20 min each - 5 presentation / 15 workshop)
- 1 x Keynote ( 50 min  - 30 presentation / 20 discussion) 

**Day 1: Platforms and Social Systems**

Full: 
- Hodges
- Tennis B 
- Halpin 

Short: 
- Rajan 
- Bennett + Peterson 

**Day 2: Science + Scholarship** 

Full:
- Wickett
- Schneider
- Hoffman 

Short:
- Chan 
- Cragin + Nunez

**Comment by organisciak** [comment]
This looks sensible. Thank you for putting it together.
